version: '3'

services:
  api:
    image: 79769827852732/user-post-fastapi:${TAG}
    build: .
    volumes:
      - .:/code
    container_name: user-post-fastapi
    env_file:
      - ./.env
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: "${ALGORITHM}"
      ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES}"
      DATABASE_URL: "${DATABASE_URL}"
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
      - user-post-fastapi-network
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    restart: always
    networks:
      - user-post-fastapi-network
    
volumes:
  postgres_data:
networks:
  user-post-fastapi-network: