"""add role column to user_table

Revision ID: eeae1ace2a08
Revises: 9694c2bdd50c
Create Date: 2026-01-10 07:21:20.213321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeae1ace2a08'
down_revision: Union[str, Sequence[str], None] = '9694c2bdd50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('role', sa.String(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'role')
    # ### end Alembic commands ###
