# Configure a persistent volume for postgres since we want to keep this data even if the postgres
# pod is deleted.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/data"

---

# I don't full understand PersistentVolumeClaims, but it seems to describe how a PersistentVolume can be
# used, such as access mode and storage. In addition the PersistentVolumeClaim seems to work like
# Services, which provide access to a Pod.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-db-pv
  storageClassName: manual
