apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: user-post-fastapi
    name: postgres-service
  namespace: default
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: postgres
    app: user-post-fastapi
  sessionAffinity: None
  type: ClusterIP