apiVersion: v1
kind: Service
metadata:
  name: user-post-fastapi-service
  labels:
    app: user-post-fastapi
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: user-post-fastapi-pod
  sessionAffinity: None
  type: LoadBalancer