apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-post-fastapi-deployment
  labels:
    app: user-post-fastapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-post-fastapi-pod
  template:
    metadata:
      labels:
        name: user-post-fastapi-pod
    spec:
      containers:
      - name: user-post-fastapi
        image: 79769827852732/user-post-fastapi:1.0.6
        ports:
        - containerPort: 8080
        env:
        # - name: DATABASE_URL
        #   # value: postgresql://userPostgres:passwordPostgres@db:5432/user_post_db
        #   valueFrom:
        #     secretKeyRef:
        #       name: user-post-secret
        #       key: DATABASE_URL
        - name: POSTGRES_USER
          # value: postgres
          valueFrom:
            secretKeyRef:
              name: user-post-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-post-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: user-post-config
              key: POSTGRES_DB
        - name: POSTGRES_SERVER
          valueFrom:
            configMapKeyRef:
              name: user-post-config
              key: POSTGRES_SERVER
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: user-post-secret
              key: SECRET_KEY
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: user-post-config
              key: ALGORITHM
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: user-post-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES